import { buildDictionary, compressText } from "./dictionary.js";
import { parseLangTarget } from "./lang.js";
import type { Sections } from "./types.js";

const SOURCE_SECTIONS = [
  "context",
  "variables",
  "goal",
  "constraints",
  "output",
] as const;

const BASE_RULES: Array<[string, string]> = [
  ["reply", "code_only"],
  ["no_prose", "true"],
  ["no_markdown", "true"],
  ["no_preamble", "true"],
  ["no_postamble", "true"],
  ["no_comments_unless_required", "true"],
  ["emit_files_under", "external/"],
];

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line.length === 0 ? line : pad + line))
    .join("\n");
}

function block(name: string, inner: string, level: number): string {
  const pad = " ".repeat(level);
  if (inner.trim().length === 0) {
    return `${pad}${name}: {\n${pad}}`;
  }
  return `${pad}${name}: {\n${indent(inner, level + 2)}\n${pad}}`;
}

export function buildPromptSection(sections: Sections): string {
  const texts = SOURCE_SECTIONS.map((name) => sections[name] ?? "").filter(
    (t) => t.trim().length > 0,
  );

  const pairs = buildDictionary(texts);
  const target = parseLangTarget(sections.lang) ?? "unknown";
  const rules: Array<[string, string]> = [["target", target], ...BASE_RULES];

  const rulesInner = rules.map(([k, v]) => `${k} = ${v}`).join("\n");

  const dictInner =
    pairs.length === 0
      ? "# (empty)"
      : pairs.map((p) => `${p.alias} = ${p.word}`).join("\n");

  const bodyChunks: string[] = [];
  for (const name of SOURCE_SECTIONS) {
    const raw = sections[name];
    if (raw === undefined || raw.trim().length === 0) continue;
    const compressed = compressText(raw, pairs)
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .join("\n");
    bodyChunks.push(block(name, compressed, 0));
  }

  const payload = [
    "# generated by ilang — do not edit",
    block("rules", rulesInner, 0),
    block("dict", dictInner, 0),
    block("body", bodyChunks.join("\n"), 0),
  ].join("\n");

  return `{\n${indent(payload, 2)}\n}`;
}
